# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code to the container
COPY . .

# Install pnpm globally
RUN npm install -g pnpm

# Install app dependencies
RUN pnpm i --force

# Expose port 8000 for the server to listen on
EXPOSE 8000

# Start the server using npm start
CMD ["pnpm", "dev"]