FROM public.ecr.aws/lambda/nodejs:18 as builder

WORKDIR /app

COPY ./api/video/upload/tiktok_initialize.ts package.json pnpm-lock.yaml ./

RUN npm i -g pnpm esbuild

RUN pnpm i

COPY . .

RUN esbuild tiktok_initialize.ts --bundle --minify --sourcemap --platform=node --target=es2020 --outfile=dist/index.js


FROM public.ecr.aws/lambda/nodejs:18

WORKDIR ${LAMBDA_TASK_ROOT}

COPY --from=builder ./app/dist/* ./

CMD ["index.handler"]