name: Deploy API to Lambdas
on: [push]
jobs:
  lambdas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 900 #15m
          aws-region: us-east-1 #Test

      - name: Bundle and Package lambdas TypeScript
        run: |
          chmod +x ./scripts/build.sh ./scripts/zip.sh
          ./scripts/build.sh
          ./scripts/zip.sh

      - name: Deploy lambdas
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
