name: Deploy UI
on: [push]
jobs:
  lambdas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install -g pnpm
          pnpm -v
          cd frontend
          pnpm install --no-frozen-lockfile

      - name: Build
        run: |
          pnpm build
          ls dist
